root_dir: ${oc.env:PROJECT_ROOT}
data_dir: ${paths.root_dir}/data/
rules_dir: ${paths.root_dir}/rules/
log_dir: ${paths.root_dir}/logs/
output_dir: ${hydra:runtime.output_dir}
work_dir: ${hydra:runtime.cwd}
config_path: ${paths.root_dir}/data/config_1.xml
